### ISSUE TITLE
Polar Area Chart 베이스라인 코드 생성

### ISSUE THREAD

**Issue by cmpark0126** [cmpark0126/billboard.js#2]
## Description
* Pie chart와 polar chart의 형태가 유사한 점이 있음
  * Pie Chart (원형, 각 항목 별로 앵글은 다르게 소비됨, 각 항목별 반지름 동일)
    ![image](https://user-images.githubusercontent.com/17241893/141688630-1ead0c69-5622-48b7-a7c9-bcde0d459880.png)
  * Polar Chart: https://www.chartjs.org/docs/latest/charts/polar.html (원형, 각 항목별 앵글은 같음, 각 항목별 반지름 다를 수 있음)
    ![image](https://user-images.githubusercontent.com/17241893/141688537-85d3c4f8-ffb4-409c-81bd-eebb769af973.png)
* 이에 pie chart 코드를 베이스라인 코드로 사용하고, 이를 점진적으로 수정하여 polar chart 개발을 진행하는 것으로 함
  * 참고 자료는 위의 링크를 참고

**Comment by cmpark0126** [comment]
@sni-J 슬랙 논의를 여기에서 이어서 진행하겠습니다.

> @sni-J  파이차트는 데이터의 크기를 각도로 표시하기 때문에 크기를 axis로 갖는 폴라차트의 베이스가 되기에는 원형이라는 점 이외에는 도움이 되지 않을 것 같습니다. 레이더 차트를 바탕으로 하되 파이차트 내의 유사 부채꼴 svg를 참고하면서 구현하는 방식이 맞지 않을까 싶네요.
> @cmpark0126 네 그렇게 진행해도 되는데요. 저는 사실 어떻게 해야할지 구체적인 감이 없어서 그럼 베이스 코드를 만드는 작업을 원준님이 해주실 수 있을까요? 저보다 구체적으로 잘 아시는거 같아서요.

**Comment by sni-J** [comment]
Radar와 Pie 모두 비교하면서 확인 중이고 고려해야할 사항 남깁니다


- Radar는 hasArcType과 hasRadar 속성을 갖는 형태
- 이 때 hasArcType은 pie, gauge 등과 같이 어느 한 축이 직선형이 아닌 케이스를 다룸
- hasRadar는 다른 'ArcType'과 달리 양에 해당하는 값이 각도가 아닌 반지름을 축으로 하는 경우를 분리한 케이스
    - 그러나 이러한 경우가 기존에는 Radar 차트가 유일했기 때문에 코드가 Radar에 특화되어 있음
    - ex) "hasArcType && hasRadar 이면 이 차트는 무조건 Radar 차트임"과 같은 방식의 코드들이 여럿 있음

&rarr; 다음과 같은 선택지가 있음
1. Radar에 연관된 모든 코드를 그대로 duplicate 후 Polar로 변경하여 베이스코드를 완성 (&larr; 시도하면서 위 사실을 발견)
2. Polar를 Radar의 하위 옵션 형태로 구현 후 나중에 분리

일단 1을 시도 중이고, 2로 우회하는 것이 더 편리할지는 진행하면서 살펴보다가 결정할 예정

**Comment by cmpark0126** [comment]
@sni-J 작업하고 계시는 내용 혹시 draft로 만들어서 이 repo PR에 올려주실 수 있나요?

**Comment by sni-J** [comment]
다방면으로 삽질 중이라 마땅한 코드상의 진척은 없어서 따로 공유하긴 어려울 것 같습니다. 업데이트 가능해지면 올릴게요.

**Comment by cmpark0126** [comment]
@sni-J 네 나중에 드래프트로라도 올릴 수 있는 수준이 되면 공유 부탁드릴게요 :) 베이스코드 작성된 것을 보고 바로 다음 작업에 들어갈 수 있도록 하고자 합니다.
