### ISSUE TITLE
마우스 hover에 따라 (1) Polar Area Chart 영역이 강조되고 , (2) 적절한 Raw Data를 보여주는 기능 추가

### ISSUE THREAD

**Issue by cmpark0126** [cmpark0126/billboard.js#8]
## Description
* 그래프와 인터렉션이 이루어지는 가장 기초적인 기능으로 아래와 같은 방식으로 action이 이루어지면 됨
![image](https://user-images.githubusercontent.com/17241893/141690510-e48d65b3-33d9-424d-b7c0-f021adda3bff.png)
![image](https://user-images.githubusercontent.com/17241893/141690534-973bb8d3-0566-4f52-a6d8-3451de03adbb.png)

**Comment by HanungLee** [comment]
#12 작업에서 이 이슈 관련 커맨트하신 내용입니다. 
아래와 같은 작업이 필요하다고 합니다. 

> src/Chart/api/focus.ts -> focus, defocus, revert에 대해서 별도 구현 필요
> -> 현재는 arc.ts의 expand/unexpand를 따르게 되어있어서 이상하게 작동할 것
